#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:require
#extension GL_EXT_shader_atomic_float: require 

#define HUAILAILIDAR

#include "../bindinglayout.h"
#include "../parameters.h"
#include "../global.glsl"
#include "../functions.glsl"
#include "../nanovdb_info.glsl"

layout(local_size_x = GROUP_SIZEX) in;


void main()
{
    //------------------------------------------------------------
    // Initialization for the position and SSBO index
    //------------------------------------------------------------
    uint bufferId = uint(gl_GlobalInvocationID.x);
    //voxelRes: voxel number in 3 dimentions
    ivec3 voxelRes = ivec3(setting.voxelSize);
    uint instanceId = voxelLinks[bufferId].instanceId;
    //-------------------------
    // various parameters index
    //-------------------------
    // VoxelInstanceLink instanceLink = instanceLinks[instanceId];
    InstanceLink instanceLink = instanceLinks[instanceId];
    MeshLink meshLink = meshLinks[instanceLink.meshId];
    uint spectralId,canopyId,bioId,typeId;
    spectralId = meshLink.spectralId;
    canopyId = meshLink.canopyId;
    bioId = meshLink.bioId;
    typeId = meshLink.type;
    if(typeId == TYPE_NULL) return;
    //-------------------------
    // various parameters associated with radiation 
    //-------------------------
    // in: incident direct+diffuse VNIR+TIR radiance
    float inShadedRad = voxelNetRads[bufferId].diffuseVrad + voxelNetRads[bufferId].diffuseTrad;
    float inSunlitRad = inShadedRad + voxelNetRads[bufferId].directTrad + voxelNetRads[bufferId].directVrad;
    float TsunlitOld,TshadedOld;
    TsunlitOld = voxelTempes[bufferId].sunlit;
    TshadedOld = voxelTempes[bufferId].shaded;
    // in: thermal emittance radiance 
    float outShadedRad = Stefen_Boltzmann(TshadedOld,0.95);
    float outSunlitRad = Stefen_Boltzmann(TsunlitOld,0.95);
    //---------------------------------------------
    // Calculate net radiation for sunlit/shaded veg/soil
    //---------------------------------------------
    float netSunlitRad,netShadedRad;
    if(typeId == TYPE_VEGETATION)
    { 
        // netSunlitRad = inSunlitRad - 2*outSunlitRad;
        // netShadedRad = inShadedRad - 2*outShadedRad;
        netSunlitRad = inSunlitRad - outSunlitRad;
        netShadedRad = inShadedRad - outShadedRad;
    }else if(typeId == TYPE_SOIL)
    {
        netSunlitRad = inSunlitRad - outSunlitRad;
        netShadedRad = inShadedRad - outShadedRad;
    }// IF TYPE

    // soil heat storage 
    float Gsunlit,Gshaded;
    if(abs(voxelHeatFlux[bufferId].Gsunlit - 0.35)<0.01) Gsunlit = netSunlitRad * 0.35;
    else Gsunlit = voxelHeatFlux[bufferId].Gsunlit;
    if(abs(voxelHeatFlux[bufferId].Gshaded - 0.35)<0.01) Gshaded = netShadedRad * 0.35;
    else Gshaded = voxelHeatFlux[bufferId].Gshaded; 



    // float Gsunlit=0,Gshaded=0;
    // Gsunlit = voxelHeatFlux[bufferId].Gsunlit;
    // Gshaded = voxelHeatFlux[bufferId].Gshaded; 
    //-------------------------------------------------------
    //  Update surface temperature : old
    //-------------------------------------------------------
    float Tsunlit,Tshaded;
    float Ta = ubom.meteo.Ta;
    float innovation1 = 0,innovation2 = 0;
    float wc = 0.2;  // update coefficient 
    float raa = voxelRaas[bufferId].raa ;
    float diffHeatfluxSunlit =  voxelHeatFlux[bufferId].LEsunlit + Gsunlit;
    float diffHeatfluxShaded =  voxelHeatFlux[bufferId].LEshaded + Gshaded;
    innovation1 = raa/ (RHOA * CP) * (netSunlitRad - diffHeatfluxSunlit);
    Tsunlit = ubom.meteo.Ta +273.15+  wc* innovation1 +(1-wc) * (TsunlitOld-273.15 - ubom.meteo.Ta);
    innovation2 = raa / (RHOA * CP) * (netShadedRad - diffHeatfluxShaded);
    Tshaded = ubom.meteo.Ta +273.15+ wc * innovation2 +(1-wc) * (TshadedOld-273.15 - ubom.meteo.Ta);
    int count = 0;
    if (abs(innovation1) > RAD_THRESHOLD) count = count + 1;
    if( abs(innovation2) > RAD_THRESHOLD) count = count + 1;

    //-------------------------------------------------------
    //  Update surface temperature : new
    //-------------------------------------------------------
    // float Tsunlit,Tshaded;
    // float Ta = ubom.meteo.Ta;
    // float e_to_q = MH20 / MAIR / ubom.meteo.p;
    // float ei_sunlit = es_fun(TsunlitOld);
    // float s_sunlit = s_fun(ei_sunlit, TsunlitOld);
    // float ei_shaded = es_fun(TshadedOld);
    // float s_shaded = s_fun(ei_shaded, TshadedOld);
    // float innovation1 = 0,innovation2 = 0;
    // float raa = voxelRaas[bufferId].raa ;
    // float rss_sunlit = voxelRsss[bufferId].sunlit;
    // float rss_shaded = voxelRsss[bufferId].shaded;
    // float diffSunlitRad = netSunlitRad - (voxelHeatFlux[bufferId].LEsunlit + Gsunlit + voxelHeatFlux[bufferId].Hsunlit);
    // float diffShadedRad = netShadedRad - (voxelHeatFlux[bufferId].LEshaded + Gshaded + voxelHeatFlux[bufferId].Hshaded);
    // float lambdas_sunlit = (2.501-0.002361*TsunlitOld)*1E6;
    // float lambdas_shaded = (2.501-0.002361*TshadedOld)*1E6;

    // // for debug
    // // voxelTempes[bufferId].sunlit = diffSunlitRad;//(RHOA*CP)/raa + RHOA*lambdas_sunlit*e_to_q*s_sunlit/(raa+rss_sunlit)+4*SIGMASB*pow(TsunlitOld,3);
    // // voxelTempes[bufferId].shaded = RHOA;//(RHOA*CP)/raa + RHOA*lambdas_shaded*e_to_q*s_shaded/(raa+rss_shaded)+4*SIGMASB*pow(TshadedOld,3);
    // // return;


    // //-------------------------------
    // // Attension!!! no emissivity
    // //-------------------------------
    // float wc = 15;
    // // if(setting.theIteration>5) wc = 0.3;
    // // if(setting.theIteration>10) wc = 0.2;
    // // if(setting.theIteration>30) wc = 0.1;

    // Tsunlit = TsunlitOld + diffSunlitRad * wc / ((RHOA*CP)/raa+
    //     RHOA*lambdas_sunlit*e_to_q*s_sunlit/(raa+rss_sunlit)+4*SIGMASB*pow(TsunlitOld,3));
    // Tshaded = TshadedOld + diffShadedRad * wc / ((RHOA*CP)/raa+
    //     RHOA*lambdas_shaded*e_to_q*s_shaded/(raa+rss_shaded)+4*SIGMASB*pow(TshadedOld,3));
    // //----------------------------------------
    // // count bad result
    // //----------------------------------------
    // int count=0;
    // if (abs(diffSunlitRad) > RAD_THRESHOLD) count = count + 1;
    // if (abs(diffShadedRad) > RAD_THRESHOLD) count = count + 1;

    // // for debug
    // // voxelTempes[bufferId].sunlit = raa;//(RHOA*CP)/raa + RHOA*lambdas_sunlit*e_to_q*s_sunlit/(raa+rss_sunlit)+4*SIGMASB*pow(TsunlitOld,3);
    // // voxelTempes[bufferId].shaded = RHOA;//(RHOA*CP)/raa + RHOA*lambdas_shaded*e_to_q*s_shaded/(raa+rss_shaded)+4*SIGMASB*pow(TshadedOld,3);
    // // return;



    //-----------------------------------------
    // adjust bad temperature 
    //-----------------------------------------
    if(Tsunlit > TMAX_THRESHOLD || Tshaded > TMAX_THRESHOLD)
    {
        Tsunlit = Ta + 2.0 + 273.15;
        Tshaded = Ta + 1.0 + 273.15;
    }
    if(Tsunlit < TMIN_THRESHOLD || Tshaded < TMIN_THRESHOLD)
    {
        Tsunlit = Ta + 2.0 + 273.15;
        Tshaded = Ta + 1.0 + 273.15;
    }

//     if(isnan(Tsunlit))
//     {
// Tsunlit = Ta + 2.0 + 273.15;
//     }
//         if(isnan(Tshaded))
//     {
// Tshaded = Ta + 2.0 + 273.15;
//     }


//     //-------------------------------------------
//     // SAVE BACK
//     //-------------------------------------------
//     // Tsunlit = diffSunlitRad;
// Tsunlit =  diffSunlitRad * wc / ((RHOA*CP)/raa+
//         RHOA*lambdas_sunlit*e_to_q*s_sunlit/(raa+rss_sunlit)+4*SIGMASB*pow(TsunlitOld,3));
    voxelTempes[bufferId].sunlit = Tsunlit;
    voxelTempes[bufferId].shaded = Tshaded;
    // count = count/2;

    // count = 100;
    atomicAdd(ebState.count,count,gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);


}