#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:require
#extension GL_EXT_shader_atomic_float: require

#define HUAILAILIDAR

#include "../bindinglayout.h"
#include "../parameters.h"
#include "../global.glsl"
#include "../bsdf.glsl"
#include "../functions.glsl"
#include "../nanovdb_info.glsl"
#include "../shade_state_voxel.glsl"
#include "../random.glsl"

PtPayload        prd;
ShadowHitPayload shadow_payload;

#include "../traceray_comp.glsl"

layout(local_size_x = GROUP_SIZEX) in;
#define MAXSTEP   100
// #define DIFFUSE_ANGLE_NUM 32
#define MAXBAND    25
#define NUM_VNIR 2001
#define NUM_BAND 2002
float GammaR[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];
float GammaT[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];

// To check if this can be to solar
bool TraversalDirection(vec3 lightDirection)
{
    //------------------------------------------------------------
    // Initialization for the position and SSBO index
    //------------------------------------------------------------
    // get bufferId, voxelPos, instanceId and typeId
    uint bufferId0 = uint(gl_GlobalInvocationID.x);
    ivec3 voxelId0 = voxelLinks[bufferId0].voxelPos;
    uint instanceId0 = voxelLinks[bufferId0].instanceId;
    uint primId0 = voxelLinks[bufferId0].primId;
    uint meshId0 = instanceLinks[instanceId0].meshId;
    uint typeId0 = meshLinks[meshId0].type;

    // Get nanoVDBLink: from voxelPos to bufferId
    NanoVDBLink nanoVDBLink = nanovdbInit();

    // get left and down position of a voxel; ray cast postion
    float scale = setting.scale;
    // vec3 semiRange = setting.voxelSize / 2.0;
    ivec3 semiRange = ivec3(floor(setting.voxelSize.x/2.0 + 0.5),
                            floor(setting.voxelSize.y/2.0 + 0.5),
                            floor(setting.voxelSize.z/2.0 + 0.5));       // voxel scene semiRange.
    vec3 voxelPos0 = vec3(voxelId0.x - semiRange.x, voxelId0.y, voxelId0.z - semiRange.z);
    if (primId0 == 0){
        voxelPos0 = vec3(voxelPos0.x + 0.5, voxelPos0.y + 0.5, voxelPos0.z + 0.5);
    }
    if (primId0 == 1){
        voxelPos0 = vec3(voxelPos0.x + 0.5, voxelPos0.y, voxelPos0.z + 0.5);
    }
    if (primId0 == 2){
        voxelPos0 = vec3(voxelPos0.x + 1, voxelPos0.y + 0.5, voxelPos0.z + 0.5);
    }
    if (primId0 == 3){
        voxelPos0 = vec3(voxelPos0.x, voxelPos0.y + 0.5, voxelPos0.z + 0.5);
    }
    if (primId0 == 4){
        voxelPos0 = vec3(voxelPos0.x + 0.5, voxelPos0.y + 1, voxelPos0.z + 0.5);
    }
    if (primId0 == 5){
        voxelPos0 = vec3(voxelPos0.x + 0.5, voxelPos0.y + 0.5, voxelPos0.z + 1);
    }
    if (primId0 == 6){
        voxelPos0 = vec3(voxelPos0.x + 0.5, voxelPos0.y + 0.5, voxelPos0.z);
    }

    ivec3 voxelPos, alignVoxelId;                       // passed and align voxel
    int bufferId, alignBufferId;                        // passed and align voxel id
    uint meshId, instanceId, canopyId, typeId;
    float alpha_toSolar = 1.0;
    float alpha_voxel = 1.0;

    // ray cast from the center position of a voxel along a specific direction
    Ray ray = Ray(voxelPos0, lightDirection);

    // This is a process toward direction step by step
    int kstep = 0;
    vec3 ffnormal;
    for (kstep = 0; kstep < setting.maxStep; kstep++)
    {
        // the transmittance inside a voxel
        alpha_voxel = 1.0;

        ClosestHit(ray, 0.001);

        // if (kstep == 0){
        //     ShadeState sstate = GetShadeState(prd);
        //     // avoid hit self
        //     ffnormal = sstate.normal;
        //     ray.origin = OffsetRay(sstate.position, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
        //     ClosestHit(ray, 0.001);
        // }

        // if (kstep == 0) continue;

        // hit nothing and return false
        if(prd.hitT == INFINITY)
        {
            // voxelDirs[bufferId0].solar = alpha_toSolar;
            alpha_toSolar = alpha_toSolar;
            atomicStore(voxelDirs[bufferId0].solar, alpha_toSolar, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
            return false;
        }

        // get hit information, especially get ffnormal to avoid hit self.
        ShadeState sstate = GetShadeState(prd);
        voxelPos = getVoxelIdSemi(sstate.position, semiRange, normalize(lightDirection), alignVoxelId);



        bufferId = nanovdbGet(nanoVDBLink, voxelPos);   // passed voxel buffer ID
        // a valid voxel and get this voxel information.
        if (bufferId >=0)
        {
            instanceId = voxelLinks[bufferId].instanceId;
            meshId = instanceLinks[instanceId].meshId;
            typeId = meshLinks[meshId].type;
            ivec3 voxelRes = ivec3(setting.voxelSize);
            uint surf1DId = SurfFlatten(voxelPos, voxelRes);
            float lad = LAD[surf1DId];
// lad = 0.3;
            if (abs(float(typeId - TYPE_VEGETATION)) < 0.1)
            {
                float pathLength = Vector2Distance(sstate.position - sstate.lastPosition);
                alpha_voxel = exp(-lad * 0.5 * pathLength * scale);
            }
            alpha_toSolar = alpha_toSolar * alpha_voxel;
            // instanceId = voxelLinks[bufferId].instanceId;
            // meshId = instanceLinks[instanceId].meshId;
            // typeId = meshLinks[meshId].type;
            // canopyId = meshLinks[meshId].canopyId;

            // if (abs(float(typeId - TYPE_VEGETATION)) < 0.1)
            // {
            //     float pathLength = Vector2Distance(sstate.position - sstate.lastPosition);
            //     alpha_voxel = exp(-canopies[canopyId].density * canopies[canopyId].G * pathLength * scale);
            // }
            // alpha_toSolar = alpha_toSolar * alpha_voxel;
        }

        alignBufferId = nanovdbGet(nanoVDBLink, alignVoxelId);


// alpha_toSolar = 45;
// break;

        // a valid voxel and get this voxel informatin
        if (alignBufferId >=0)
        {
            if (alpha_toSolar <= 0.001) break;

            instanceId = voxelLinks[alignBufferId].instanceId;
            meshId = instanceLinks[instanceId].meshId;
            typeId = meshLinks[meshId].type;

            if (abs(float(typeId - TYPE_SOIL)) < 0.1)
            {
                alpha_toSolar = 0.0;
                break;
            }

            if (abs(float(typeId - TYPE_VEGETATION)) < 0.1)
            {
                // next cast
            }
        }



        // avoid hit self
        ffnormal = sstate.normal;
        ray.origin = OffsetRay(sstate.position, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
    }

    // atomicAdd(voxelDirs[bufferId0].solar, alpha_toSolar, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    // alpha_toSolar = 99;
    atomicStore(voxelDirs[bufferId0].solar, alpha_toSolar, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    return true;
}

void main() {
    // solar direction
    vec3 directions = normalize(lightSet.direction);
    uint bufferId0 = uint(gl_GlobalInvocationID.x);
    if(directions.y < 0.01)
    {
        
        voxelDirs[bufferId0].solar = 0.0;
    }else{
        voxelDirs[bufferId0].solar = 0.0;
        TraversalDirection(directions);
    }
}