#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:require
#extension GL_EXT_shader_atomic_float: require 

#define HUAILAILIDAR 1

#include "../bindinglayout.h"
#include "../parameters.h"
#include "../global.glsl"
#include "../bsdf.glsl"
#include "../functions.glsl"
#include "../nanovdb_info.glsl"
#include "../shade_state_voxel.glsl"
#include "../random.glsl"

PtPayload        prd;
ShadowHitPayload shadow_payload;

#include "../traceray_comp.glsl"

layout(local_size_x = GROUP_SIZEXY, local_size_y = GROUP_SIZEXY) in;
#define MAXSTEP   100
// #define DIFFUSE_ANGLE_NUM 32
#define MAXBAND    25
#define NUM_VNIR 2001
#define NUM_BAND 2002
float wavelength = 10500;
float LST;
float LSTSum;

bool Voxel_raytracing(Ray ray, NanoVDBLink nanoVDBLink)
{
    // initialized the transmittance and accumulated radiance 
    float alpha_toSensor = 1.0;
    float alpha_toSolar, alpha_voxel;
    LST = 0.0;
    vec3 ffnormal;
    float scale = setting.scale;			// scale
    ivec3 voxelPos, alignVoxelId;           // passed and align voxel pos 
    int bufferId, alignBufferId;            // passed bufferID and align bufferid
    uint instanceId, typeId, meshId;        // voxel Id through voxelLink and instanceLink.
    uint canopyId, thermalId, spectralId;   // voxel spectral, thermal, canopy ID.
	float pl_toSolar, pl_toSensor;			// hotspot parameters. pathlenght.
    Canopy canopy;							// store canopy information
    ivec3 semiRange = ivec3(floor(setting.voxelSize.x/2.0 + 0.5),
                            floor(setting.voxelSize.y/2.0 + 0.5),
                            floor(setting.voxelSize.z/2.0 + 0.5));       // voxel scene semiRange.

    // 散射项函数与其归一化条件
    vec2 gamma = scattering_phase_function_direct_XZY_paper(normalize(lightSet.direction), normalize(-sensorMatrix.direction));
    vec2 gammaMax = scattering_phase_function_direct_XZY_paper(normalize(lightSet.direction), normalize(-lightSet.direction));
    // vec2 gamma = scattering_phase_function_direct_XZY(normalize(lightSet.direction), -normalize(sensorMatrix.direction));
    // vec2 gammaMax = scattering_phase_function_direct_XZY(normalize(lightSet.direction), -normalize(lightSet.direction));
    float gammaValue = (gamma.x) * 1.0 + (gamma.y) * 0.5;
    float gammaMaxValue = (gammaMax.x) * 1.0 + (gammaMax.y) * 0.5;
    // float gammaValue = gamma.y * 0.5;
    // float gammaMaxValue = gammaMax.y * 0.5;

    float phase = gammaValue / gammaMaxValue;
// LST = phase;
// return false;

    if (phase > 1) phase = 1.0;
    if (phase < 0.0) phase = 0.0;
        // GammaSR[jangle] = gamma.x;
        // GammaST[jangle] = gamma.y;
    for(int kstep = 0;kstep<=setting.maxStep;kstep++)
    // for(int kstep = 0;kstep<=1;kstep++)
    {
        alpha_voxel = 1.0;
        ClosestHit(ray, 0.001);

        ///////////////////////////////////////////////////
		/// sky case (sky -> sensor).
		/// hit sky or out of scene, then return true. 
		/// the sky contribution is added in solar file.
		///////////////////////////////////////////////////
        if(prd.hitT == INFINITY)
        {
            LST += 0; 
            return true;
        }

        ///////////////////////////////////////////////////
		/// Turbid or facet ground case (j -> sensor).
		///////////////////////////////////////////////////
		/// get hit information.
		ShadeState sstate = GetShadeState(prd);

        ivec3 alignVoxelId;
        voxelPos = getVoxelIdSemi(sstate.position, semiRange, normalize(ray.direction), alignVoxelId);

		bufferId = nanovdbGet(nanoVDBLink, voxelPos);  
        alignBufferId = nanovdbGet(nanoVDBLink, alignVoxelId);

// // check EB error
// float netRad = voxelNetRads[alignBufferId].diffuseVrad + voxelNetRads[alignBufferId].diffuseTrad 
//         + voxelNetRads[alignBufferId].directTrad + voxelNetRads[alignBufferId].directVrad;
// float Gsunlit = 0;
// LST = voxelPos.y;
// return false;

// ivec3 voxelRes = ivec3(setting.voxelSize);
// uint surf1DId = SurfFlatten(voxelPos, voxelRes);
// float lad = LAD[surf1DId];
// LST = ubom.meteo.Ta;
// return false;



        if(bufferId >= 0)
		{
            ivec3 voxelRes = ivec3(setting.voxelSize);
            uint surf1DId = SurfFlatten(voxelPos, voxelRes);
            float lad = LAD[surf1DId];
// lad = 0.3;
			instanceId = voxelLinks[bufferId].instanceId;
            meshId = instanceLinks[instanceId].meshId;

			typeId = meshLinks[meshId].type;
			canopyId = meshLinks[meshId].canopyId;
			spectralId = meshLinks[meshId].spectralId;
			thermalId = meshLinks[meshId].thermalId;

			canopy = canopies[canopyId];
            uint spectralBase = spectralId * NUM_BAND;


            float envTemp = Inv_Stefen_Boltzmann(voxelNetRads[bufferId].diffuseTrad, 1);
            
            // LST = voxelHeatFlux[bufferId].Gshaded;
            // LST = voxelDirs[bufferId].solar;
            // LST = voxelTempes[bufferId].shaded;
            // LST = voxelRaas[bufferId].raa;

            
            if(typeId == TYPE_VEGETATION)
			{

				float pathLength = Vector2Distance(sstate.position - sstate.lastPosition);// * 0.2; //!!!!需要改回去！！！
                float lai = canopy.lai;
                // if (kstep > 1){
                //     alpha_voxel = exp(-lad * 0.5 * pathLength * scale);
                // }
				alpha_voxel = exp(-lad * 0.5 * pathLength * scale);

				alpha_toSolar = voxelDirs[bufferId].solar;
                // float alpha_voxel_ = exp(-lad * 0.5 * pathLength * 0.5 * scale);
                // float alpha_toSensor_ = alpha_toSensor * alpha_voxel_;
// LST = lai;
// break;
                float hspot = canopy.hspot;
				if(alpha_toSensor < 0.001) {
                    // LST = 5;
                    break;
                }
                // if(alpha_toSensor_ < 0.001) {

                // }
                

				// this is used for the hotspot effect
				if(alpha_toSolar < 0.001) pl_toSolar = 10000.0;
				else pl_toSolar = -log(alpha_toSolar) / 0.5 / DENSITY;
				if(alpha_toSensor < 0.001) pl_toSensor = 10000.0;
				else pl_toSensor = -log(alpha_toSensor) / 0.5 / DENSITY;

				// float hotspot = Hotspot_Kuusk(normalize(lightSet.direction), -normalize(ray.direction), pl_toSolar, pl_toSensor, DENSITY, HSPOT);

                float hotspot = Hotspot_Kuusk(normalize(lightSet.direction), normalize(sensorMatrix.direction), pl_toSolar, pl_toSensor, DENSITY, hspot);
                if (checkSameDirection(normalize(lightSet.direction), normalize(sensorMatrix.direction)) && abs(alpha_toSolar - alpha_toSensor) < EPSION_2)
                {
                    alpha_toSolar = alpha_toSensor;
                    hotspot = alpha_toSensor;
                }

                float fhotspot = hotspot / alpha_toSensor * phase;

                // float fhotspot = hotspot / alpha_toSensor;

                if (fhotspot > 1) fhotspot = 1.0;
                if (fhotspot < 0.0) fhotspot = 0.0;

               // hotspot = hotspot * phase;///0.5;

// LST = hotspot / alpha_toSensor;
// break;

                if ((pl_toSensor > 999) || (pl_toSolar>999))
                {
                    hotspot = 0.0;
                }


                float refl = spectralMaterials[spectralBase + NUM_VNIR].reflectance;
                float trans = spectralMaterials[spectralBase + NUM_VNIR].transmittance;

                
                // get sunlit and shaded fraction and mixed them for an average result.
                float sunlitTemperature = voxelTempes[bufferId].sunlit;
                float shadedTemperature = voxelTempes[bufferId].shaded;
                // float sunlitTemperature = 300; 
                // float shadedTemperature = 300;

                // hot spot
                float radianceDirect = 0.0;
                float thermalRadiance = Planck(wavelength, sunlitTemperature) * fhotspot * alpha_toSensor
                                        + Planck(wavelength, shadedTemperature) * (alpha_toSensor * (1 - fhotspot));
                float p = calReCor(lai);
                float s = ((refl + trans) - p* (refl + trans)) / (1 - p* (refl + trans));
                s= (1 - p *(refl + trans)); 
                radianceDirect = thermalRadiance * ((1 - refl - trans))* (1 - alpha_voxel);
                                
                LST += radianceDirect; // debug
// if (kstep == 5){
    // LST = Planck(wavelength, sunlitTemperature);
    // break;
// // }
// LST = Planck(wavelength, envTemp);
// break;

                LST += Planck(wavelength, envTemp) * (1 - alpha_voxel) * refl * alpha_toSensor;


				alpha_toSensor = alpha_toSensor * alpha_voxel;
			}
			// if(typeId == TYPE_VEGETATION)
			// {

			// 	float pathLength = Vector2Distance(sstate.position - sstate.lastPosition);// * 0.2; //!!!!需要改回去！！！
			// 	alpha_voxel = exp(-canopies[canopyId].density * canopies[canopyId].G * pathLength * scale);

			// 	alpha_toSolar = voxelDirs[bufferId].solar;

			// 	if(alpha_toSensor < 0.001) break;

			// 	// this is used for the hotspot effect
			// 	if(alpha_toSolar < 0.0001) pl_toSolar = 10000.0;
			// 	else pl_toSolar = -log(alpha_toSolar) / canopy.G / 1.0;
			// 	if(alpha_toSensor < 0.0001) pl_toSensor = 10000.0;
			// 	else pl_toSensor = -log(alpha_toSensor) / canopy.G / 1.0;
			// 	float hotspot = Hotspot_Kuusk(normalize(lightSet.direction), -normalize(ray.direction), pl_toSolar, pl_toSensor, canopy.density, HSPOT);

            //     if ((pl_toSensor > 999) || (pl_toSolar>999))
            //     {
            //         hotspot = 0.0;
            //     }


            //     float refl = spectralMaterials[spectralBase + NUM_VNIR].reflectance;
            //     float trans = spectralMaterials[spectralBase + NUM_VNIR].transmittance;

                
            //     // get sunlit and shaded fraction and mixed them for an average result.
            //     float sunlitTemperature = voxelTempes[bufferId].sunlit;
            //     float shadedTemperature = voxelTempes[bufferId].shaded;

            //     // hot spot
            //     float radianceDirect = 0.0;
            //     float thermalRadiance = Planck(wavelength, sunlitTemperature) * hotspot
            //                             + Planck(wavelength, shadedTemperature) * (alpha_toSensor - hotspot);
            //     radianceDirect = thermalRadiance * (1 - refl - trans) * (1 - alpha_voxel);
                                
            //     LST += radianceDirect; // debug

			// 	alpha_toSensor = alpha_toSensor * alpha_voxel;
			// }
			// if(typeId == TYPE_SOIL)
			// {
			// 	alpha_toSolar = voxelDirs[bufferId].solar;

			// 	// this is used for the hotspot effect
			// 	if(alpha_toSolar < 0.0001) pl_toSolar = 10000.0;
			// 	else pl_toSolar = -log(alpha_toSolar) / LEAFG / 1.0;
			// 	if(alpha_toSensor < 0.0001) pl_toSensor = 10000.0;
			// 	else pl_toSensor = -log(alpha_toSensor) / LEAFG / 1.0;
			// 	float hotspot = Hotspot_Kuusk(normalize(lightSet.direction), -normalize(ray.direction), pl_toSolar, pl_toSensor, 1.0, HSPOT);

            //     if ((pl_toSensor > 999) || (pl_toSolar>999))
            //     {
            //         hotspot = 0.0;
            //     }

            //     // LST += 10;
            //     // break;

            //     float refl = spectralMaterials[spectralBase + NUM_VNIR].reflectance;
            //     float trans = spectralMaterials[spectralBase + NUM_VNIR].transmittance;

            //     //// solar and emitted case
            //     //// (solar -> i -> o) + self-emitter(i -> o); i is soil.
            //     float radianceDirect = 0.0;
            //     // get sunlit and shaded fraction and mixed them for an average result.
            //     float sunlitTemperature = voxelTempes[bufferId].sunlit;
            //     float shadedTemperature = voxelTempes[bufferId].shaded;

            //     // hotspot
            //     float thermalRadiance = Planck(wavelength, sunlitTemperature) * hotspot 
            //                             + Planck(wavelength, shadedTemperature) * (alpha_toSensor - hotspot);
            //     radianceDirect = thermalRadiance * (1 - refl - trans);
                
            //     //LST = canopy.G;
            //     LST += radianceDirect;
            //     // LST = 1;
            //  //   LST = voxelDirs[bufferId].solar;
            //     //               uint instanceId = voxelLinks[bufferId].instanceId;
            //     // uint meshId = instanceLinks[instanceId].meshId;
            //     // LST = meshLinks[meshId].type;
			// 	break;
			// }
		}

        
        if (alignBufferId >=0)
        {
            instanceId = voxelLinks[alignBufferId].instanceId;
            meshId = instanceLinks[instanceId].meshId;

			typeId = meshLinks[meshId].type;
			spectralId = meshLinks[meshId].spectralId;
			thermalId = meshLinks[meshId].thermalId;

            uint spectralBase = spectralId * NUM_BAND;

            float envTemp = Inv_Stefen_Boltzmann(voxelNetRads[alignBufferId].diffuseTrad, 1);


            if (typeId == TYPE_VEGETATION)
            {
                // do nothing and continue next ray
            }

            if (typeId == TYPE_SOIL)
            {

//  LST = 3;
//  return false;

                alpha_toSolar = voxelDirs[alignBufferId].solar;

                

                // this is used for the hotspot effect
				if(alpha_toSolar < 0.0001) pl_toSolar = 10000.0;
				else pl_toSolar = -log(alpha_toSolar) / LEAFG / DENSITY;
				if(alpha_toSensor < 0.0001) pl_toSensor = 10000.0;
				else pl_toSensor = -log(alpha_toSensor) / LEAFG / DENSITY;
                
                
                // float hotspot = Hotspot_Kuusk(normalize(lightSet.direction), -normalize(ray.direction), pl_toSolar, pl_toSensor, DENSITY, HSPOT);
                float hotspot = Hotspot_Kuusk(normalize(lightSet.direction), normalize(sensorMatrix.direction), pl_toSolar, pl_toSensor, DENSITY, HSPOT);
                                
                if (checkSameDirection(normalize(lightSet.direction), normalize(sensorMatrix.direction)) && abs(alpha_toSolar - alpha_toSensor) < EPSION_2)
                {
                    alpha_toSolar = alpha_toSensor;
                    hotspot = alpha_toSensor;
                }
//  LST = hotspot / alpha_toSensor;
// //  LST = alpha_toSolar;
//  return false;
                if ((pl_toSensor > 999) || (pl_toSolar>999))
                {
                    hotspot = 0.0;
                }

                float refl = spectralMaterials[spectralBase + NUM_VNIR].reflectance;
                float trans = spectralMaterials[spectralBase + NUM_VNIR].transmittance;

                //// solar and emitted case
                //// (solar -> i -> o) + self-emitter(i -> o); i is soil.
                float radianceDirect = 0.0;
                // get sunlit and shaded fraction and mixed them for an average result.
                float sunlitTemperature = voxelTempes[alignBufferId].sunlit;
                float shadedTemperature = voxelTempes[alignBufferId].shaded;
                // float sunlitTemperature = 320;
                // float shadedTemperature = 300;

                // hotspot
                float thermalRadiance = Planck(wavelength, sunlitTemperature) * hotspot 
                                        + Planck(wavelength, shadedTemperature) * (alpha_toSensor - hotspot);
                radianceDirect = thermalRadiance * (1 - refl - trans);

//  LST = voxelLinks[alignBufferId].primId;
//  return false;
                
                LST += radianceDirect;

                // LST += Planck(wavelength, envTemp)  * refl;
                LST += Planck(wavelength, envTemp)  * refl * alpha_toSensor;

                // LST = Planck(wavelength, envTemp)  * refl * alpha_toSensor + Planck(wavelength, sunlitTemperature);
                // LST = ubom.meteo.Ta;

				break;
            }
            
        }
        // LST = 55;
        // break;
		//// change ray origin position to hit position; and avoid self collide.
		ray = Ray(sstate.position, ray.direction);
		ffnormal = sstate.normal;
		ray.origin = OffsetRay(ray.origin, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
    }
}

void SamplePixel(vec2 imageCoords,vec2 sizeImage,int smpl)
{
    LST = 0.0;
    // 每次光线的随机/波动进行光滑
    vec2 subpixel_jitter = smpl == 0 ? vec2(0.5f, 0.5f) : vec2(rand(prd.seed), rand(prd.seed));
    // vec2 subpixel_jitter = vec2(0.5f, 0.5f) ;
	// 计算样本的波动，范围 [-1 .. 1]
	const vec2 pixelCenter = vec2(imageCoords) + subpixel_jitter;
	const vec2 inUV        = pixelCenter / vec2(sizeImage.xy);
	vec2       d           = inUV * 2.0 - 1.0;

	// 计算光线的初始化和方向
	vec4 origin    = sensorMatrix.viewInverse * vec4(0, 0, 0, 1);
	vec4 target    = sensorMatrix.projInverse * vec4(d.x, d.y, 1, 1);
	vec4 direction = sensorMatrix.viewInverse * vec4(normalize(target.xyz), 0);

    // direction = vec4(normalize(-sensorMatrix.direction.xyz), 0);

	// // 景深-平行投影还是中心投影
	// vec3  focalPoint        = sensorMatrix.focalDist * direction.xyz;
	// float cam_r1            = rand(prd.seed) * M_TWO_PI;
	// float cam_r2            = rand(prd.seed) * sensorMatrix.aperture;
	// vec4  cam_right         = sensorMatrix.viewInverse * vec4(1, 0, 0, 0);
	// vec4  cam_up            = sensorMatrix.viewInverse * vec4(0, 1, 0, 0);
	// vec3  randomAperturePos = (cos(cam_r1) * cam_right.xyz + sin(cam_r1) * cam_up.xyz) * sqrt(cam_r2);
	// vec3  finalRayDir       = normalize(focalPoint - randomAperturePos);
    NanoVDBLink nanoVDBLink = nanovdbInit();

    // 光线位置和方向
	//Ray ray = Ray(origin.xyz + randomAperturePos, finalRayDir);
    vec3 directionv = normalize(direction.xyz);
	Ray ray = Ray(origin.xyz, directionv);

    Voxel_raytracing(ray, nanoVDBLink);
   // LST = 1.0;
}

void main()
{
    // image imageSize
	ivec2 imageRes    = ivec2(setting.imageSize);
    // image coordinate from 1-imageSize
    ivec2 imageCoords = ivec2(gl_GlobalInvocationID.xy);  //SampleSizzled();
    
    uint temp = uint(setting.imageSize.x * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x);
    prd.seed = tea(temp, setting.frame * setting.n_sample);
    LSTSum = 0.0;

    // int bufferId = int((imageCoords.y * imageRes.x + imageCoords.x ));
    // LST = imageRes.y;
    // atomicStore(outImage[bufferId], LST, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsRelease);

    for(int smpl = 0; smpl < setting.n_sample; smpl++)
    {
        SamplePixel(imageCoords, imageRes, smpl);
        LSTSum += LST;
    }

    LST = LSTSum/setting.n_sample;
    
    int bufferId = int((imageCoords.y * imageRes.x + imageCoords.x ));
    atomicStore(outImage[bufferId], LST, gl_ScopeDevice, gl_StorageSemanticsBuffer, gl_SemanticsRelease);

}