#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:require
#extension GL_EXT_shader_atomic_float: require 

#define VOXEL_LST_BIND_ININDEX
#define VOXELLST 1

#include "../bindinglayout.h"
#include "../parameters.h"
#include "../global.glsl"
#include "../settings.h"
#include "../functions.glsl"
#include "../nanovdb_info.glsl"
#include "../shade_state_voxel.glsl"

PtPayload        prd;
ShadowHitPayload shadow_payload;

#include "../traceray_comp.glsl"

layout(local_size_x = GROUP_SIZEX) in;
#define MAXSTEP   100
// #define DIFFUSE_ANGLE_NUM 32
#define MAXBAND    25
#define NUM_VNIR 2001 
#define NUM_BAND 2162
#define NUM_TIR 161
float GammaR[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];
float GammaT[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];
// from solar direction to selected direction;
float GammaSR[DIFFUSE_ANGLE_NUM];
float GammaST[DIFFUSE_ANGLE_NUM];


// diffuse directions
void scattering_phase_function_diffuse()
{
  for(int iangle = 0;iangle < DIFFUSE_ANGLE_NUM; iangle++)
  {
    vec3 directioni = normalize(DIFFUSE_DIRECTIONS[iangle]);
    for(int jangle = 0;jangle < DIFFUSE_ANGLE_NUM; jangle++)
    {
      vec3 directionj = normalize(DIFFUSE_DIRECTIONS[jangle]);
      vec2 Gamma = scattering_phase_function_direct_XZY(directioni,directionj);
      GammaR[iangle*DIFFUSE_ANGLE_NUM + jangle] = Gamma.x;
      GammaT[iangle*DIFFUSE_ANGLE_NUM + jangle] = Gamma.y;
    }
  }
}

// diffuse directions
void scattering_phase_function_solar_diffuse()
{
  vec3 directioni = normalize(lightSet.direction);
  for(int jangle = 0;jangle < DIFFUSE_ANGLE_NUM; jangle++)
  {
      vec3 directionj = normalize(DIFFUSE_DIRECTIONS[jangle]);
      vec2 Gamma = scattering_phase_function_direct_XZY(directioni,directionj);
      GammaSR[jangle] = Gamma.x;
      GammaST[jangle] = Gamma.y;
  }
}


bool voxel_raytracing_diffuse(vec3 voxelPos0, uint bufferId0, NanoVDBLink nanoVDBLink,
 int kiter,int kband,float Esun,float Esky)
{


  
  // vec3 semiRange = setting.scale * setting.voxelSize/2.0; 
    float scale = setting.scale;
    vec3 semiRange = scale * setting.voxelSize/2.0;
  // semiRange = vec3(0,0,0);
  // i:induced direction for the selected voxel; 0 original
  // j:induced direction for the traveled voxel;
  // s:solar direction
  vec3 directioni,directioni0,directionj,directionj0;
  vec3 directions = normalize(lightSet.direction);
  int bufferId,alignBufferId;
  uint spectralId,thermalId,canopyId;
  vec2 gammart;
  float alpha_voxel,alpha_toSolar,alpha_toVoxel;
  uint typeId;
  uint instanceId,lastInstanceId,alignInstanceId;
  uint bufferIdPlus0;
  ivec3 voxelPos,alignVoxelId;
  float pl_toSolar,pl_toVoxel,refl,trans,emis,gamma,wavelength;
  float sunlitTemperature,sunlitRadiance,shadedTemperature,shadedRadiance,thermalRadiance;
  InstanceLink instanceLink;
  MeshLink meshLink;
  Canopy canopy;

  
    //ivec3 voxelId0 = voxelLinks[bufferId0].voxelPos;
    uint instanceId0 = voxelLinks[bufferId0].instanceId;
    uint meshId0 = instanceLinks[instanceId0].meshId;
    uint typeId0 = meshLinks[meshId0].type;
  
  bool isvegfirst = true;


  ////////////////////////////////////////////////////////
  //  Iteration in difuse angle
  ////////////////////////////////////////////////////////
  for(uint iangle = 0; iangle < DIFFUSE_ANGLE_NUM; iangle++)
  {
    directioni0 = DIFFUSE_DIRECTIONS[iangle];
    directioni = normalize(directioni0);


    Ray ray = Ray(voxelPos0, directioni);
    // vec3 ffnormal0  = vec3(0,1,0);
    // ray.origin = OffsetRay(ray.origin, dot(ray.direction, ffnormal0) > 0 ? ffnormal0 : -ffnormal0);



    alpha_toSolar = 1.0;
    alpha_toVoxel = 1.0;
		voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced = 0.0;
    // if((typeId0 == TYPE_SOIL) && (directioni0.y < 0))
    // {
    //   continue;
    // }


//----------------------------------
          //  uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
          // atomicAdd(voxelRads[index].induced,
          //     Esky,
          //     gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
          //     continue;
//---------------------------------------


    /////////////////////////////////////////////////////
    /// Iteration in travel step
    /////////////////////////////////////////////////////
    int kstep = 0;
    vec3 ffnormal;


    for(kstep = 0;kstep<=setting.maxStep;kstep++)
    { 


      alpha_voxel = 1.0;
      ClosestHit(ray,0.01);
      if(prd.hitT == INFINITY)
      {
        //////////////////////////////
        /// Atmospheric case
        /////////////////////////////

        // add save the sky contribution
        // sky contribution: lightSet.Rli*waveSets[kband].diffuse*0.001
        if(directioni0.y >= 0)
        {
           float skyrad = alpha_toVoxel*Esky;
          uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
          atomicAdd(voxelRads[index].induced,
              skyrad,
              gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
        }
        alpha_toVoxel = 0.001;
        break;
      }


    // float skyrad = 1;
    // uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
    // atomicAdd(voxelRads[index].induced,
    //     skyrad,
    //     gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    //     break;

      // get hit information
      ShadeState sstate = GetShadeState(prd);
       voxelPos = getVoxelIdSimple(sstate.position,semiRange,setting.scale);
        //voxelPos = getPassedVoxelId(sstate.position, setting.scale,directioni);
        bufferId = nanovdbGet(nanoVDBLink,voxelPos);


    //   if(bufferId == bufferId0){
    //         float skyrad = 100;
    // uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
    // atomicAdd(voxelRads[index].induced,
    //     skyrad,
    //     gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    //     break;
    //   }else{
    //                 float skyrad = 200;
    // uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
    // atomicAdd(voxelRads[index].induced,
    //     skyrad,
    //     gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    //     break;
    //   }

      //////////////////////////////
      /// Trubid case
      /////////////////////////////
      if(sstate.typeId == TYPE_VEGETATION)
      {
        // get voxelPos and alignVoxelId
        //voxelPos = getPassedVoxelId(sstate.position, setting.scale,directioni);
        // voxelPos = getVoxelIdSemi(sstate.position,semiRange,setting.scale,directioni,alignVoxelId);
        voxelPos = getVoxelIdSemi(sstate.position,semiRange,setting.scale,directioni,alignVoxelId);
        // get bufferId and alignBufferId;
        // if bufferId/alignBufferId = -1, this voxel is blank;
        bufferId = nanovdbGet(nanoVDBLink,voxelPos);
        alignBufferId = nanovdbGet(nanoVDBLink,alignVoxelId);
        if(kstep ==0) lastInstanceId = -1;
        if(bufferId >= 0)
        {
          // a valid voxel and get voxel information 
          // such as instanceId, typeId, spectralId, thermalId, canopyId
           InstanceLink instanceLink = instanceLinks[instanceId];
            MeshLink meshLink = meshLinks[instanceLink.meshId];
            uint spectralId,canopyId,bioId,typeId;
            spectralId = meshLink.spectralId;
            canopyId = meshLink.canopyId;
            bioId = meshLink.bioId;
            typeId = meshLink.type;
          // the condition (instanceId == lastInstanceId) for path from penetrating part 
          // the condition (instanceId == alignInstanceId) due to a face corresponding to two facets belong to two align voxels, respectively
          // if((instanceId == lastInstanceId || instanceId == alignInstanceId))
          // {
             // get the pathLength 
            float pathLength = Vector2Distance(sstate.position - sstate.lastPosition);
            canopy = canopies[canopyId];
            alpha_voxel = exp(-canopy.density * canopy.G * pathLength);
            alpha_toSolar = voxelDirs[bufferId].solar;

          // if(isvegfirst==true)
          // {
          //   alpha_toVoxel = alpha_voxel;
          // }


            // get the phase function for solar direction to induced direction 
            gammart.x = GammaSR[iangle];
            gammart.y = GammaST[iangle];
            sunlitTemperature = voxelTempes[bufferId].sunlit;
            shadedTemperature = voxelTempes[bufferId].shaded;
            /////////////////////////////////////////////////////
            /// Iteration in BAND
            /////////////////////////////////////////////////////

              // THERMAL
              // wavelength = waveSets[kband].wavelength;
              // sunlitRadiance = Planck(wavelength,sunlitTemperature);
              // shadedRadiance = Planck(wavelength,shadedTemperature);
              sunlitRadiance = Stefen_Boltzmann(sunlitTemperature,1);
              shadedRadiance = Stefen_Boltzmann(shadedTemperature,1);

              thermalRadiance = (1-alpha_toSolar)*shadedRadiance + alpha_toSolar*sunlitRadiance;
              // SPECTRAL
              trans = spectralMaterials[spectralId*NBAND+kband].transmittance;
              refl = spectralMaterials[spectralId*NBAND+kband].reflectance;
              emis = 1 - trans - refl;
              float gamma = abs(gammart.x)*(refl + trans) + abs(gammart.y)*trans;  
              gamma = clamp(gamma,0,1);
              float radiance = 0;
               //////////////////////////////
              /// Multiple case
              /////////////////////////////
              // if(kiter > 0)
              // {
              //   for(int jangle=0;jangle<DIFFUSE_ANGLE_NUM;jangle++)
              //   {
              //       float radiancej = voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].cumulated;
              //       directionj0 = (DIFFUSE_DIRECTIONS[jangle]);
              //       gammart.x = GammaR[iangle*DIFFUSE_ANGLE_NUM+jangle];
              //       gammart.y = GammaT[iangle*DIFFUSE_ANGLE_NUM+jangle];
              //       gamma =   abs(gammart.x)*(refl + trans)+ abs(gammart.y)*trans;  
              //       gamma = clamp(gamma,0,1);
              //       radiance= radiance + radiancej * gamma* alpha_toVoxel*(1-alpha_voxel);  
              //   }
              //   radiance = radiance / DIFFUSE_ANGLE_NUM;
              // }
              //////////////////////////////
              // emitter
              /////////////////////////////
              // thermalRadiance = 100;
              radiance+= (thermalRadiance*(1-alpha_voxel)*emis* alpha_toVoxel);
              // radiance = shadedTemperature;
              //////////////////////////////
              /// Solar 
              /////////////////////////////
              radiance += (alpha_toSolar * gamma * Esun * alpha_toVoxel *(1-alpha_voxel));  
              //////////////////////////////
              /// Save back
              /////////////////////////////
              atomicAdd(voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced,radiance,
                  gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
            alpha_toVoxel = alpha_toVoxel * alpha_voxel;
            if(alpha_toVoxel < 0.01) break; 
          // }// if outside
        } //if voxel
        else
        {
            atomicAdd(voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced,5,
                  gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
        }
      }// if vegetation
      else
      {
        //////////////////////////////
        /// facet case
        /////////////////////////////
        voxelPos = getVoxelIdSimple(sstate.position,semiRange,setting.scale);
        //voxelPos = getPassedVoxelId(sstate.position, setting.scale,directioni);
        bufferId = nanovdbGet(nanoVDBLink,voxelPos);
        alpha_toSolar = voxelDirs[bufferId].solar;

        vec3 wo = directioni;  // FROM SELECTED VOXEL OUT TO HIT FACET  
        vec3 wi = lightSet.direction; // FROM SELECTED VOXEL OUT TO SOLAR
        vec3 ffnormal = sstate.normal;
        bool inSameSides = IsSameSide(wo,wi,ffnormal);
        uint spectralIdBase = sstate.spectralId*NBAND;
        uint instanceId0 = voxelLinks[bufferId0].instanceId;
        if(kstep == 0 && sstate.instanceId == instanceId0) continue;
        // THERMAL
        sunlitTemperature = voxelTempes[bufferId].sunlit;
        shadedTemperature = voxelTempes[bufferId].shaded;
        float radiance=0;

          // wavelength = waveSets[kband].wavelength;
          // sunlitRadiance = Planck(wavelength,sunlitTemperature);
          // shadedRadiance = Planck(wavelength,shadedTemperature);

          sunlitRadiance = Stefen_Boltzmann(sunlitTemperature,1);
          shadedRadiance = Stefen_Boltzmann(shadedTemperature,1);
          thermalRadiance = (1-alpha_toSolar)*shadedRadiance + alpha_toSolar*sunlitRadiance;
          // SPECTRAL
          trans = spectralMaterials[spectralId*NBAND+kband].transmittance;
          refl = spectralMaterials[spectralId*NBAND+kband].reflectance;
          emis = 1 - trans - refl;
          // //////////////////////////////
          // /// Multiple case
          // /////////////////////////////
          // if(kiter > 0)
          // {
          //   for(int jangle=0;jangle<DIFFUSE_ANGLE_NUM;jangle++)
          //   {
          //       directionj0 = (DIFFUSE_DIRECTIONS[jangle]);
          //       bool inSameSide = isSameSide(directioni,directionj0,ffnormal);
          //       if(!inSameSide) continue;
          //       float radiancej = voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].cumulated;
          //       radiance= radiance + radiancej * refl* alpha_toVoxel;  
          //   }
          //   radiance = radiance/DIFFUSE_ANGLE_NUM;
          // }
          
          ////////////////////////////////
          // SOLAR CASE
          ///////////////////////////////
          if(inSameSides)
          {
            radiance += (refl * Esun * alpha_toSolar * alpha_toVoxel);
          }
          // ////////////////////////////////
          // //emitter
          // ////////////////////////////////
          radiance+= (thermalRadiance * emis * alpha_toVoxel);
          //////////////////////////////
          /// Save back
          /////////////////////////////
          atomicAdd(voxelRads[bufferId0*DIFFUSE_ANGLE_NUM+iangle].induced,radiance,
              gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);

          alpha_toVoxel = 0;
          break;
      }// if facet

      // if(alignBufferId>=0)
      // {
      //    alignInstanceId = bufferVoxelLinks[alignBufferId].instanceId;
      // }
      // lastInstanceId = instanceId;

      // alpha_toVoxel = alpha_toVoxel * alpha_voxel;
      // if(alpha_toVoxel < 0.01) break; 

      ray = Ray(sstate.position,directioni);
      ffnormal  = sstate.normal;
      ray.origin = OffsetRay(ray.origin, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
    }

    // if((kstep >= setting.maxStep) && (alpha_toVoxel > 0.05))
    // {
    //     float skyrad = alpha_toVoxel*Esky;
    //     //skyrad = 0.5;
    //     uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
    //     atomicAdd(voxelRads[index].induced,
    //         skyrad,
    //         gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    // }
  }
  return false;
}


void main()
{
    //------------------------------------------------------------
    // Initialization for the position and SSBO index
    //------------------------------------------------------------
    // get bufferId, voxelPos, instanceId and typeId
    uint bufferId0 = (gl_GlobalInvocationID.x);
    ivec3 voxelId0 = voxelLinks[bufferId0].voxelPos;
    uint instanceId0 = voxelLinks[bufferId0].instanceId;
    uint meshId0 = instanceLinks[instanceId0].meshId;

    InstanceLink instanceLink0 = instanceLinks[instanceId0];
    MeshLink meshLink0 = meshLinks[meshId0];
    uint typeId0 = meshLink0.type;
    uint spectralId0 = meshLink0.spectralId;
    int primId0 = voxelLinks[bufferId0].primId;
    vec3 ffnormal0 = vec3(0,1,0);
    // if(primId0 == 0) {ffnormal0 = vec3(0,0,0); }
    // atomicAdd(voxelNetRads[bufferId0].diffuseTrad, primId0, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    // return;
    // Get nanoVDBLink: from voxelPos to bufferId
    NanoVDBLink nanoVDBLink = nanovdbInit();
    // get center position of a voxel
    // float scale = setting.scale;
    // vec3 semiRange = scale * setting.voxelSize/2.0; 
    // vec3 voxelPos0 = vec3((voxelId0.x+0.5)*scale-semiRange.x, (voxelId0.y+0.5)*scale,(voxelId0.z+0.5)*scale-semiRange.z );
    float scale = setting.scale;
    vec3 semiRange = scale * setting.voxelSize/2.0;
    vec3 voxelPos0 = vec3(scale * voxelId0.x + scale/2.0-semiRange.x,
                          scale * voxelId0.y,
                          scale * voxelId0.z + scale/2.0-semiRange.z); 
    uint spectralIdBase = spectralId0 * NBAND;
    if(typeId0 == TYPE_VEGETATION)
    {
      voxelPos0.y = voxelPos0.y + scale/2.0;
    }

    // reset the voxelRads in VNIR band
    // for(uint kband=NUM_VNIR;kband < NUM_BAND;kband++)
    //   for(uint iangle=0;iangle < DIFFUSE_ANGLE_NUM;iangle++)
    //   {
    //     uint index = bufferId0*32*2162+kband*32+iangle;
    //     voxelRads[index].cumulated=0.0;
    //   }

    //------------------------------------------------------------
    // An iteration process for diffuse scattering function
    //------------------------------------------------------------
    // pre-calcuation Gamma 
    scattering_phase_function_diffuse();
    scattering_phase_function_solar_diffuse(); 
    
    voxelNetRads[bufferId0].diffuseTrad = 0 ;

    int kband_start = 0, kband_end = 0;
    // int kstep = setting.bandTstep;
    int kbandj = NUM_VNIR;
    int kband_center = NUM_VNIR;


    float wavelength = waveSets[kbandj].wavelength;
    float Esun = 0;
    float Esky = lightSet.Rli;

        for(int kiter=0;kiter< 1;kiter++)
        {
            voxel_raytracing_diffuse(voxelPos0, bufferId0, nanoVDBLink, kiter,kband_center,Esun,Esky);
            groupMemoryBarrier();  
            barrier();

            for(uint iangle=0;iangle < DIFFUSE_ANGLE_NUM;iangle++)
            {
                uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
                voxelRads[index].cumulated = voxelRads[index].induced;
            }
        }// for iteration

    //------------------------------------------------------------
    // accumulated incident radiation to four components: direct/diffuse VNIN/TIR radiation
    //------------------------------------------------------------

        float rads=0,radtemp = 0,absorb;
        // iteration in diffuse angle
        int effeNum = 0;
        for(uint iangle=0;iangle < DIFFUSE_ANGLE_NUM;iangle++)
        {

           vec3 directioni0 = DIFFUSE_DIRECTIONS[iangle];
           vec3  directioni = normalize(directioni0);
           float abc = cross0(directioni0,ffnormal0);
           if(abc <=0) {continue;}
            uint index = bufferId0*DIFFUSE_ANGLE_NUM+iangle;
            radtemp = voxelRads[index].cumulated;
            if(radtemp>0.5)
            {
              effeNum = effeNum + 1;
              rads = rads + radtemp;
            }


        }// for iteration

        if(effeNum >0){
          if (typeId0 == TYPE_SOIL)
          {
              rads = rads/effeNum;
          }
          else
          {rads = rads/effeNum;}
        }
        
        
        // absorb = 1- spectralMaterials[spectralIdBase+kband_center].transmittance - 
        //     spectralMaterials[spectralIdBase+kband_center].reflectance;
        // rads = rads *absorb;


        atomicAdd(voxelNetRads[bufferId0].diffuseTrad, rads, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
    //}// for band

    // float rads = typeId0;
    // atomicAdd(voxelNetRads[bufferId0].diffuseTrad, rads, gl_ScopeDevice,gl_StorageSemanticsBuffer,gl_SemanticsRelaxed);
}