#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_ray_query : enable
#extension GL_ARB_shader_clock : enable                 // Using clockARB
#extension GL_EXT_shader_image_load_formatted : enable  // The folowing extension allow to pass images as function parameters

#extension GL_NV_shader_sm_builtins : require     // Debug - gl_WarpIDNV, gl_SMIDNV
#extension GL_ARB_gpu_shader_int64 : enable       // Debug - heatmap value
#extension GL_EXT_shader_realtime_clock : enable  // Debug - heatmap timing

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_debug_printf : enable
#extension GL_KHR_memory_scope_semantics:require
#extension GL_EXT_shader_atomic_float: require 

#define VOXEL_LST_BIND_ININDEX
#define VOXELLST 1

#include "../bindinglayout.h"
#include "../parameters.h"
#include "../global.glsl"
#include "../bsdf.glsl"
#include "../functions.glsl"
#include "../nanovdb_info.glsl"
#include "../shade_state_voxel.glsl"
#include "../random.glsl"

PtPayload        prd;
ShadowHitPayload shadow_payload;

#include "../traceray_comp.glsl"

layout(local_size_x = GROUP_SIZEX) in;
#define MAXSTEP   100
// #define DIFFUSE_ANGLE_NUM 32
#define MAXBAND    25
#define NUM_VNIR 2001 
#define NUM_BAND 2162
#define NUM_TIR 161
float GammaR[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];
float GammaT[DIFFUSE_ANGLE_NUM * DIFFUSE_ANGLE_NUM];

// To check if this can be to solar 
bool TraversalDirection(vec3 lightDirection)
{
    //------------------------------------------------------------
    // Initialization for the position and SSBO index
    //------------------------------------------------------------
    // get bufferId, voxelId, instanceId and typeId
    uint bufferId0 = uint(gl_GlobalInvocationID.x);
    ivec3 voxelId0 = voxelLinks[bufferId0].voxelId;
     uint instanceId0 = voxelLinks[bufferId0].instanceId;
    uint typeId0 = instanceLinks[instanceId0].type;

    // Get nanoVDBLink: from voxelId to bufferId 
    NanoVDBLink nanoVDBLink = nanovdbInit();

    // get center position of a voxel
    float scale = setting.scale;
    vec3 semiRange = scale * setting.voxelSize/2.0;
    vec3 voxelPos0 = vec3(scale * voxelId0.x + scale/2.0-semiRange.x,
                          scale * voxelId0.y,
                          scale * voxelId0.z + scale/2.0-semiRange.z); 
    if(typeId0 == TYPE_VEGETATION)
    {
      voxelPos0.y = voxelPos0.y + scale/2.0;
    }

    ivec3 voxelId;                      // current passed voxel
    int bufferId;                       // passed voxel Id
    uint instanceId, canopyId, typeId;  //passed voxel Id through voxelLink and instanceLink.
    float alpha_toSolar = 1.0;
    float alpha_voxel = 1.0;
    
    // ray cast from the center position of a voxel along a specific direction
    Ray ray = Ray(voxelPos0, normalize(lightDirection));

    // This is a process toward direction step by step
    int kstep = 0;
    vec3 ffnormal;
    for(kstep = 0; kstep<setting.maxStep; kstep++)
    {
        // the transmittance inside a voxel
        alpha_voxel = 1.0;

        ClosestHit(ray);
        // hit nothing and return false.
        if(prd.hitT == INFINITY)
        {
            voxelDirs[bufferId0].solar = alpha_toSolar;
            return false;
        }

        // get hit information, especially get ffnormal to avoid hit self.
        ShadeState sstate = GetShadeState(prd);
        // voxelId = getPassedVoxelId(sstate.position, scale, normalize(lightDirection));
        vec3 alignVoxelId;
        voxelId = getVoxelIdSemi(sstate.position,semiRange,setting.scale,normalize(lightDirection),alignVoxelId);
		

        bufferId = nanovdbGet(nanoVDBLink, voxelId);
        
        // a valid voxel and get this voxel information.
        if(bufferId >= 0)
        {
            instanceId = voxelLinks[bufferId].instanceId;
            typeId = instanceLinks[instanceId].type;
            canopyId = instanceLinks[instanceId].canopyId;
            // if soil, this voxel transmittance is 1.
            if(typeId == TYPE_SOIL)
            {
                if(kstep == 0)  alpha_voxel = 1;
                else 
                {
                    alpha_toSolar = 0.0;
                    break;
                }
            }
            if(typeId == TYPE_VEGETATION)
            {
                float pathLength = Vector2Distance(sstate.position - sstate.lastPosition);
                alpha_voxel = exp(-canopies[canopyId].density * canopies[canopyId].G * pathLength);
            }
        }
        alpha_toSolar = alpha_toSolar * alpha_voxel;

        if(alpha_toSolar <= 0.01) break;
        // avoid hit self.
        ffnormal  = sstate.normal;
        ray.origin = OffsetRay(sstate.position, dot(ray.direction, ffnormal) > 0 ? ffnormal : -ffnormal);
    }

    voxelDirs[bufferId0].solar = alpha_toSolar;

    return true;

}

void main()
{
  // solar direction
  vec3 directions = normalize(lightSet.direction);
  
  if(directions.y < 0.01) 
  {
      uint bufferId0 = uint(gl_GlobalInvocationID.x);
      voxelDirs[bufferId0].solar = 0.0;
  }else
  TraversalDirection(directions);
}
